# 1

In [ ]:
# 응답 설문 문항
question = ['Q2', 'Q3', 'Q4', 'Q5', 'Q6_1', 'Q6_2', 'Q6_3', 'Q6_4', 'Q6_5', 'Q6_6',
       'Q6_7', 'Q6_8', 'Q6_9', 'Q6_10', 'Q6_11', 'Q6_12', 'Q7_1', 'Q7_2',
       'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q8', 'Q9', 'Q10_1', 'Q10_2',
       'Q10_3']

In [ ]:
single_choice = [] # 하나의 응답만 할 수 있는 문제를 넣을 새로운 리스트 생성
for i in question:
    if "_" not in i:
        single_choice.append(i)

print(single_choice)

['Q2', 'Q3', 'Q4', 'Q5', 'Q8', 'Q9']

# 2

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/healthexp.csv")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [ ]:
df1 = df[df['Year']>=2011] # 2011년이상의 값으로 된 새로운 데이터프레임 생성
df1 = df1.dropna() # 요약 통계량을 구하기 전 있을 수도 있는 결측값 제거
df1

     Year        Country  Spending_USD  Life_Expectancy
214  2011         Canada      4228.962             81.4
215  2011        Germany      4566.678             80.5
216  2011         France      4161.698             82.3
217  2011  Great Britain      3495.652             81.0
218  2011          Japan      3740.756             82.7
219  2011            USA      8079.467             78.7
220  2012         Canada      4336.249             81.6
221  2012        Germany      4745.546             80.6
222  2012         France      4299.434             82.1
223  2012  Great Britain      3614.131             81.0
224  2012          Japan      3970.765             83.2
225  2012            USA      8346.064             78.8
226  2013         Canada      4428.753             81.7
227  2013        Germany      4951.677             80.6
228  2013         France      4544.964             82.3
229  2013  Great Britain      3667.636             81.1
230  2013          Japan      4308.252             83.4
231  2013            USA      8519.620             78.8
232  2014         Canada      4536.810             81.8
233  2014        Germany      5151.709             81.2
234  2014         France      4626.679             82.8
235  2014  Great Britain      3758.935             81.4
236  2014          Japan      4328.364             83.7
237  2014            USA      8925.879             78.9
238  2015         Canada      4635.285             81.9
239  2015        Germany      5295.975             80.7
240  2015         France      4667.156             82.4
241  2015  Great Britain      3805.820             81.0
242  2015          Japan      4515.556             83.9
243  2015            USA      9355.118             78.7
244  2016         Canada      5044.275             82.0
245  2016        Germany      5669.064             81.0
246  2016         France      4928.128             82.7
247  2016  Great Britain      3960.141             81.2
248  2016          Japan      4295.858             84.1
249  2016            USA      9717.649             78.7
250  2017         Canada      5150.470             81.9
251  2017        Germany      5970.163             81.1
252  2017         France      5005.756             82.7
253  2017  Great Britain      4059.125             81.3
254  2017          Japan      4412.852             84.2
255  2017            USA     10046.472             78.6
256  2018         Canada      5308.356             82.0
257  2018        Germany      6281.840             81.0
258  2018         France      5099.306             82.8
259  2018  Great Britain      4189.708             81.3
260  2018          Japan      4554.276             84.3
261  2018            USA     10451.386             78.7
262  2019         Canada      5189.721             82.2
263  2019        Germany      6407.928             81.3
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

In [ ]:
# groupby함수를 이용해서 구하기

df1.groupby(["Year","Country"])["Life_Expectancy"].mean().unstack()

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

In [ ]:
# pivot_table 이용해서 구하기

import pandas as pd
pd.pivot_table(df1,index = ["Year"],columns = ['Country'], values="Life_Expectancy", aggfunc = "mean")

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

# 3

## 1. 데이터 분석 환경 구성
### 1.1 무엇을 분석할 것인가? 데이터 분석을 위한 환경 만들기
* 공공데이터 포털에서 다양한 데이터를 다운받아서 데이터를 분석할 수 있다.
* 아나콘다를 설치하여 제공해주는 다양한 패키지(numpy,pandas,tensorflow 등)를 이용하여 데이터 분석을 할 수 있다.

### 1.2 아나콘다 소개및 주피터 노트북 사용법
#### 1. 학습 목표

* 아나콘다를 설치하고, 주피터 노트북을 사용하는 방법을 이해할 수 있다.

#### 2. 핵심 키워드
* 주피터 랩/ 주피터 노트북
* 마크다운
* 셀 추가/편집/삭제
* 커널
* extension

#### 3. 학습내용
* 아나콘다 설치
    * 아나콘다는 파이썬/R과 관련된 다양한 패키지들을 관리하고 있습니다.
    * 자신의 OS에 맞게 다운받아서 설치할 수 있습니다. (Windows, macOS, Linux)
    
    
* 주피터 노트북 활용
    * 주피터 노트북을 실행한 후 작업할 새로운 폴더를 만드는 것이 좋다.
    * 파이썬3의 노트북을 실행하려면 `New -> Python3`를 클릭하면 된다.
    
    
* 주피터 노트북 다양한 단축키
    * enter : 편집상태로 변환
    * Shift + Enter : 셀이 실행이 되고 커서가 다음 셀로 이동
    * Ctrl + Enter : 셀이 실행되고 커서가 그 셀에 유지
    * a : 위에 셀 한 개 추가
    * b : 아래 셀 한 개 추가
    * dd : 셀 삭제
    * m : 셀을 마크다운 셀로 변환
    * n : 다양한 주피터 노트북의 단축키를 확인
    
    
* 마크다운
    * 코드와 함께 문서화를 할 수 있다.
    
    
* 주피터 노트북의 다양한 메뉴탭 활용
    * View -> Toggle Line Numbers : 라인 넘버를 확인
    * Kernel -> Restart & Clear Output : 커널과 결과를 초기화
    
    

```
Tip!!!!!!

Nbextensions -> Table Of Contents의 기능을 활용하면 index 기능을 활용할 수 있다.
```

## 2 . 데이터 분석 준비하기
### 2.1 데이터 분석을 위한 파이썬 속성 코스
#### 1. 학습 목표
* 데이터 분석에 필요한 파이썬의 기초를 학습한다.

#### 2. 핵심 키워드
* import
* boolan
* data type
* list
* for
* if
* len
* split
* join

#### 3. 학습내용
* Zen of Python
    * 파이썬의 철학이 담겨있다
    * `import this`
    * Beautiful is better than ugly 등등
    
    
* import
    * 파이썬의 라이브러리나 패키지를 가져올 수 있다.

    
* boolean
    * Ture -> 1 / False -> 0
    * `Ture == "1"` -> False
    
    
* String
    * lower() : 모두 소문자로 만들기
    * upper() : 모두 대문자로 만들기
    
    
* lists
    * appedn() : 리스트에 원소를 추가시켜주는 함수
    
    
* 제어문(조건문, 반복문)
    * 조건문 : if
    * 반복문 : for
    * enumerate() : 인덱스 번호와 원소를 같이 출력
```
for i in lang:
    if i == "python" :
        print("python")
    else:
        print("기타")
```


* 문자열
    * strip() : 앞뒤 공백 제거
    * len() : 문자열 길이
    * split() : 공백으로 문자열 분리
    

* 슬라이싱, startswith, in
    * startswith() : 특정 문자가 포함되는지 여부 확인
    * 특정 문자 in 문자열 : 특정 문자를 포함하고 있는지 여부 확인

### 2.2 판다스 치트시트를 활용한 기초 익히기
#### 1. 학습 목표
* 판다스 치트시트를 활용하여 기초를 학습

#### 2. 핵심 키워드
* pandas
* dataframe
* series
* sort
* drop
* groupby
* pivot table
* plot

#### 3. 학습내용
* Pandas : 수식으로 계산할 수 있고 시각화도 할 수 있는 데이터 분석 도구
* `import pandas as pd` : 판다스 불러오기(as pd : pandas를 pd로 별칭)
* DataFrame
    * 2차원 행렬구조
    

* Series
    * 1차원 벡터구조
    * 대괄호를 하나 더 쓰게 되면 DataFrame형태로 출력
    

* Summarize Data
    * value_counts() : categorical한 값의 빈도수 구하기


* Reshaping
    * sort_values() : 특정 컬럼을 기준으로 정렬
    * `ascending = False` 파라미터를 추가하면 역순으로 정렬
    * drop() : 해당부분 버리기 ( axis = 0 : 행, axis = 1 : 열)
    

* Group Data
    * groupby()
    * pivot_table()
    

* Ploting
    * plot() ; 꺽은선 그래프
    * plot().bar : 막대 그래프
    * plot().denstiy : 밀도 그래프
    * 이외에도 다양한 그래프 그리기 가능!!

### 2.3 파일 경로 설정 방법
#### 1. 학습 목표
* 데이터 파일의 경로를 설정하는 방법을 학습

#### 2. 핵심 키워드
* %mv
* %pwd
* %is
* pd.read_csv
* cp949

#### 3. 학습내용
* 사용할 데이터를 다운받는다.
* 현재 작업하고 있는 주피터 노트북의 경로를 확인한다.
    * %pwd로 경로 확인이 가능하다.
    * %mv로 파일을 옮기는 것이 가능하나 개인마다 파일을 다운받는 위치가 다르기 때문에 pwd로 경로를 확인한 후 그 경로에 직접 데이터를 옮겨주는 것이 좋다.
* 확인된 경로에 data 폴더를 만들어준다.
* data 폴더 안에 다운받은 데이터 파일을 옮겨준다.
* 파일을 불러온다.
    * pd.read_csv("data/파일명",encoding = "cp949")
    * csv 파일을 불러올 때 한글 파일 인코딩을하지 않으면 오류가 난다.

## 4

In [1]:
%pwd # 현재 열려있는 파일의 폴더 경로

'/content'

In [ ]:
# 현재 파일 경로에 data 폴더를 만든 후 다운받은 데이터 파일을 옮겨준다.
import pandas as pd

# 파일 불러오기
df = pd.read_csv('data/인천광역시_대중교통 이용 만족도 지하철_20200421.csv', encoding = "cp949")
df

,특성별(1),특성별(2),지하철 이용함,지하철 이용하지 않음,매우 만족 (퍼센트),약간 만족 (퍼센트),보통 (퍼센트),약간 불만족 (퍼센트),매우 불만족 (퍼센트),5점 평균 (점)
0,군구별,중구,93.1,6.9,13.2,28.7,32.8,16.6,8.8,3.21
1,군구별,동구,95.1,4.9,23.2,34.9,32.2,6.9,2.8,3.69
2,군구별,미추홀구,93.4,6.6,17.7,40.5,34.9,4.7,2.2,3.67
3,군구별,연수구,94.3,5.7,24.5,34.7,29.4,7.0,4.4,3.68
4,군구별,남동구,94.8,5.2,22.1,34.8,30.6,9.2,3.3,3.63
5,군구별,부평구,97.4,2.6,24.3,34.8,32.7,7.0,1.2,3.74
6,군구별,계양구,97.6,2.4,31.2,28.9,28.0,9.3,2.6,3.77
7,군구별,서구,95.2,4.8,13.3,32.2,35.5,13.0,6.0,3.34
8,군구별,강화군,32.7,67.3,6.6,15.3,32.3,18.6,27.3,2.55
9,군구별,옹진군,73.1,26.9,13.8,30.0,41.8,10.2,4.2,3.39
10,성별,남자,93.0,7.0,21.1,34.1,32.1,9.0,3.8,3.60
11,성별,여자,94.2,5.8,20.9,34.0,32.5,8.9,3.7,3.60
12,연령별,13~19세,96.8,3.2,29.5,28.4,32.1,8.1,1.9,3.76
13,연령별,20~29세,97.2,2.8,21.2,33.8,32.4,9.4,3.3,3.60
14,연령별,30~39세,93.6,6.4,18.5,35.3,33.6,8.8,3.8,3.56
15,연령별,40~49세,93.8,6.2,19.5,34.7,32.8,8.9,4.1,3.57
16,연령별,50~59세,93.2,6.8,20.4,34.2,32.3,9.7,3.3,3.59
17,연령별,60세 이상,90.2,9.8,21.5,34.5,30.8,8.5,4.8,3.60
18,학력별,초졸이하,88.4,11.6,23.8,32.1,32.4,7.9,3.7,3.64
19,학력별,중졸,93.2,6.8,22.2,30.6,34.2,9.6,3.3,3.59
20,학력별,고졸,94.4,5.6,20.4,34.2,33.1,8.8,3.5,3.59
21,학력별,대졸이상,94.5,5.5,20.5,35.4,30.7,9.4,4.1,3.59
22,직업별,전문관리,93.9,6.1,20.4,35.7,30.8,8.9,4.2,3.59
23,직업별,사무,95.6,4.4,19.0,36.6,29.8,10.3,4.4,3.55
24,직업별,서비스판매,92.5,7.5,21.0,33.7,31.4,9.6,4.3,3.57
25,직업별,농어업,52.0,48.0,20.6,21.8,34.5,16.4,6.7,3.33
26,직업별,기능노무,92.5,7.5,19.2,33.5,35.5,8.3,3.5,3.56
27,직업별,학생,97.7,2.3,27.4,31.3,30.4,9.0,1.9,3.73
28,직업별,주부,94.0,6.0,20.2,34.0,33.5,9.0,3.4,3.59
29,직업별,무직/기타,92.6,7.4,21.0,33.9,33.0,8.1,4.0,3.60
30,월평균소득별,100만원 미만,89.6,10.4,22.1,31.1,33.3,8.0,5.5,3.56
31,월평균소득별,100~200만원 미만,92.6,7.4,21.3,33.6,32.9,8.0,4.3,3.60
32,월평균소득별,200~300만원 미만,93.4,6.6,19.0,32.6,34.5,10.2,3.6,3.53
33,월평균소득별,300~400만원 미만,94.6,5.4,21.8,33.8,32.3,8.3,3.9,3.61
34,월평균소득별,400~500만원 미만,95.2,4.8,20.8,36.4,32.2,7.7,2.8,3.65
35,월평균소득별,500~600만원 미만,93.5,6.5,21.1,35.4,31.6,8.7,3.3,3.62
36,월평균소득별,600~700만원 미만,95.4,4.6,20.7,35.2,30.4,10.6,3.1,3.60
37,월평균소득별,700만원 이상,93.8,6.2,22.0,34.2,29.1,11.2,3.6,3.60
38,주거형태별,단독주택,85.4,14.6,17.6,34.9,34.3,8.8,4.4,3.53
39,주거형태별,아파트,95.0,5.0,22.3,34.6,30.1,9.2,3.8,3.63
40,주거형태별,연립/다세대주택,94.3,5.7,19.3,32.0,36.5,8.8,3.3,3.55
41,주거형태별,기타,93.0,7.0,20.1,34.4,33.9,7.8,3.8,3.59
42,주거점유형태별,자가,93.4,6.6,21.6,34.5,31.6,8.8,3.5,3.62
43,주거점유형태별,전세,94.5,5.5,20.1,34.3,33.1,8.8,3.7,3.58
44,주거점유형태별,월세 및 기타,93.7,6.3,19.2,31.6,34.5,9.9,4.9,3.50
45,가구원수별,1인,91.4,8.6,18.6,32.6,33.1,9.1,6.6,3.47
46,가구원수별,2인,91.4,8.6,20.7,34.8,31.4,9.0,4.1,3.59
47,가구원수별,3인,94.3,5.7,21.1,33.8,32.9,9.1,3.1,3.61
48,가구원수별,4인,95.8,4.2,21.3,34.7,31.8,8.9,3.3,3.62
49,가구원수별,5인 이상,93.9,6.1,23.1,32.2,33.3,8.8,2.5,3.65